### ISSUE TITLE
UnicodeDecodeError - update() cannot decode UTF-8 to ASCII

### ISSUE THREAD

**Issue by NobleKangaroo** [manbearwiz/youtube-dl-server#104]
Attempting to run a Docker container when a `yt-dlp` update is available results in `UnicodeDecodeError` thrown:

``` bash
$ docker run --rm -it --name youtube-dl kmb32123/youtube-dl-server
Unable to find image 'kmb32123/youtube-dl-server:latest' locally
latest: Pulling from kmb32123/youtube-dl-server
530afca65e2e: Pull complete 
cc8c14b1a767: Pull complete 
bd99fa58365b: Pull complete 
777a82aef543: Pull complete 
0c721bc97b97: Pull complete 
7ed5b0d022db: Pull complete 
f92844afe46d: Pull complete 
4f4fb700ef54: Pull complete 
f30b09a441d2: Pull complete 
40f473ba52d3: Pull complete 
2870a28307a4: Pull complete 
Digest: sha256:07f2b234f074f06bb365c6bc996bcf253ade45fa7a12031db07b8a139987f69b
Status: Downloaded newer image for kmb32123/youtube-dl-server:latest
Updating youtube-dl to the newest version
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 407, in main
    run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/./youtube-dl-server.py", line 141, in <module>
    update()
  File "/usr/src/app/./youtube-dl-server.py", line 75, in update
    print(output.decode("ascii"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 176: ordinal not in range(128)
```

It seems the output of the `python -m pip install --update yt-dlp` command contains a non-ASCII character any time the package is updated. This is likely due to special characters that are used to represent progress bars, color codes, etc. Output which triggers this error is below:

```txt
b'Requirement already satisfied: yt-dlp in /usr/local/lib/python3.10/site-packages (2022.7.18)\nCollecting yt-dlp\n  Downloading yt_dlp-2022.8.8-py2.py3-none-any.whl (2.7 MB)\n     \xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81 2.7/2.7 MB 11.7 MB/s eta 0:00:00\nRequirement already satisfied: websockets in /usr/local/lib/python3.10/site-packages (from yt-dlp) (10.3)\nRequirement already satisfied: mutagen in /usr/local/lib/python3.10/site-packages (from yt-dlp) (1.45.1)\nRequirement already satisfied: brotli in /usr/local/lib/python3.10/site-packages (from yt-dlp) (1.0.9)\nRequirement already satisfied: certifi in /usr/local/lib/python3.10/site-packages (from yt-dlp) (2022.6.15)\nRequirement already satisfied: pycryptodomex in /usr/local/lib/python3.10/site-packages (from yt-dlp) (3.15.0)\nInstalling collected packages: yt-dlp\n  Attempting uninstall: yt-dlp\n    Found existing installation: yt-dlp 2022.7.18\n    Uninstalling yt-dlp-2022.7.18:\n      Successfully uninstalled yt-dlp-2022.7.18\nSuccessfully installed yt-dlp-2022.8.8\n'
```

Specifically, the character resulting from the bytes at 176 through 178 (`\xe2\x94\x81`) is [box drawings heavy horizontal](https://www.compart.com/en/unicode/U+2501), which cannot be decoded using ASCII.

Suggest changing https://github.com/manbearwiz/youtube-dl-server/blob/0307880b5cf69d642b78be6ccabef8d0ac17e92e/youtube-dl-server.py#L75 to use UTF-8 instead of ASCII:
```py
def update():
    try:
        output = subprocess.check_output(
            [sys.executable, "-m", "pip", "install", "--upgrade", "yt-dlp"]
        )

        print(output.decode("utf-8"))
    except subprocess.CalledProcessError as e:
        print(e.output)
```

**Comment by NobleKangaroo** [comment]
Resolved pending acceptance of #105
