### ISSUE TITLE
The `python-multipart` library must be installed to use form parsing

### ISSUE THREAD

**Issue by notDavid** [manbearwiz/youtube-dl-server#197]
Hi there,

i get this error since a few days... any idea what might be going on?

The error only seems to occur if i use the Shortcut on my iPad. Adding an url via the web interface is fine.

It seems to use `http://x.x.x.x:yyyy/api/downloads` as url for the api, did that change maybe?

(running the latest docker image: `nbr23/youtube-dl-server:yt-dlp`.

Thank you!

<details>
  <summary>youtube-dl-server.log</summary>

  ```log
youtube-dl-server  | Using configuration file /app_config/config.yml
youtube-dl-server  | Using yt-dlp module
youtube-dl-server  | Started dl worker 0
youtube-dl-server  | Started dl worker 1
youtube-dl-server  | Started download threads
youtube-dl-server  | Started jobs manager thread
youtube-dl-server  | INFO:     Started server process [1]
youtube-dl-server  | INFO:     Waiting for application startup.
youtube-dl-server  | INFO:     Application startup complete.
youtube-dl-server  | INFO:     Uvicorn running on http://0.0.0.0:9090 (Press CTRL+C to quit)
youtube-dl-server  | INFO:     172.19.0.1:41988 - "POST /api/downloads HTTP/1.1" 500 Internal Server Error
youtube-dl-server  | ERROR:    Exception in ASGI application
youtube-dl-server  | Traceback (most recent call last):
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
youtube-dl-server  |     result = await app(  # type: ignore[func-returns-value]
youtube-dl-server  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
youtube-dl-server  |     return await self.app(scope, receive, send)
youtube-dl-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
youtube-dl-server  |     await self.middleware_stack(scope, receive, send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
youtube-dl-server  |     raise exc
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
youtube-dl-server  |     await self.app(scope, receive, _send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 83, in __call__
youtube-dl-server  |     await self.app(scope, receive, send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
youtube-dl-server  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
youtube-dl-server  |     raise exc
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
youtube-dl-server  |     await app(scope, receive, sender)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
youtube-dl-server  |     await self.middleware_stack(scope, receive, send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
youtube-dl-server  |     await route.handle(scope, receive, send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
youtube-dl-server  |     await self.app(scope, receive, send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
youtube-dl-server  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
youtube-dl-server  |     raise exc
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
youtube-dl-server  |     await app(scope, receive, sender)
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
youtube-dl-server  |     response = await func(request)
youtube-dl-server  |                ^^^^^^^^^^^^^^^^^^^
youtube-dl-server  |   File "/usr/src/app/ydl_server/views.py", line 196, in api_queue_download
youtube-dl-server  |     data = await request.form()
youtube-dl-server  |            ^^^^^^^^^^^^^^^^^^^^
youtube-dl-server  |   File "/usr/local/lib/python3.12/site-packages/starlette/requests.py", line 259, in _get_form
youtube-dl-server  |     assert (
youtube-dl-server  | AssertionError: The `python-multipart` library must be installed to use form parsing.
  ```
</details>

**Comment by manbearwiz** [comment]
Can you pull latests and try again? I had upgraded starlette to 0.37.1 before upgrading python-multipart to 0.0.9 so there was a window with broken builds but that should be fixed by now. https://github.com/encode/starlette/blob/7533b61a34f8b0dcb5fc35c717d458439f0baf18/docs/release-notes.md?plain=1#L31
