### ISSUE TITLE
Soundcloud always fails - requested format not available

### ISSUE THREAD

**Issue by NaturalCarr** [manbearwiz/youtube-dl-server#38]
Whenever I submit a soundcloud link, youtube-dl fails. here are the logs:

`192.168.1.202 - - [29/May/2019 03:07:08] "GET /youtube-dl/static/style.css HTTP/1.1" 200 134
192.168.1.202 - - [29/May/2019 03:07:08] "GET /favicon.ico HTTP/1.1" 404 746
192.168.1.202 - - [29/May/2019 03:08:01] "GET /youtube-dl HTTP/1.1" 304 0
Added url https://soundcloud.com/the-sarcastic-ashole to the download queue
192.168.1.202 - - [29/May/2019 03:08:13] "POST /youtube-dl/q HTTP/1.1" 200 101
[soundcloud:user] the-sarcastic-ashole: Downloading user info
[soundcloud:user] 149716153: Downloading track page 1
[soundcloud:user] 149716153: Downloading track page 2
[download] Downloading playlist: Sarcastic Sounds (All)
[soundcloud:user] playlist Sarcastic Sounds (All): Collected 18 video ids (downloading 18 of them)
[download] Downloading video 1 of 18
[soundcloud] the-sarcastic-ashole/sarcastic-sounds-i-miss-you-now-on-spotify: Downloading webpage
[soundcloud] the-sarcastic-ashole/sarcastic-sounds-i-miss-you-now-on-spotify: Downloading info JSON
[soundcloud] 600013758: Downloading track url
[soundcloud] 600013758: Downloading m3u8 information
[soundcloud] 600013758: Downloading m3u8 information
[soundcloud] 600013758: Downloading JSON metadata
[soundcloud] 600013758: Downloading JSON metadata
[soundcloud] 600013758: Downloading JSON metadata
ERROR: requested format not available

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
return self.process_video_result(ie_result, download=download)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1634, in process_video_result
expected=True)
youtube_dl.utils.ExtractorError: requested format not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "./youtube-dl-server.py", line 60, in dl_worker
download(url, options)
File "./youtube-dl-server.py", line 106, in download
ydl.download([url])
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
url, force_generic_extractor=self.params.get('force_generic_extractor', False))
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1006, in process_ie_result
extra_info=extra)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 868, in process_ie_result
extra_info=extra_info)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
self.report_error(compat_str(e), e.format_traceback())
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
self.trouble(error_message, tb)
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: requested format not available
`

**Comment by blackerking** [comment]
At the moment SOundcloud didn't work with the browser but with the binarys itself.

**Comment by manbearwiz** [comment]
tested working with latest
