### ISSUE TITLE
Exception in Thread for lengthy YouTube videos

### ISSUE THREAD

**Issue by aspiziri** [manbearwiz/youtube-dl-server#58]
I seem to be hitting an issue when downloading lengthy YouTube videos (1.5-2 hours). The download begins fine and will grab a couple hundred MB before hitting an error and exiting. I've tried restarting multiple times and I get the same result each time (though the amount that downloads before the error varies every time - 300MB, 850MB, etc).

`192.168.1.42 - - [23/Feb/2020 16:50:13] "GET /youtube-dl HTTP/1.1" 304 0
Added url https://www.youtube.com/watch?v=CNUTlKqSO-I to the download queue
192.168.1.42 - - [23/Feb/2020 16:50:28] "POST /youtube-dl/q HTTP/1.1" 200 107
[youtube] CNUTlKqSO-I: Downloading webpage
[youtube] CNUTlKqSO-I: Downloading video info webpage
[download] Destination: /youtube-dl/youtube/Above & Beyond Acoustic - Full Concert Film Live from Porchester Hall (Official) [CNUTlKqSO-I].f137.mp4
[download] Destination: /youtube-dl/youtube/Above & Beyond Acoustic - Full Concert Film Live from Porchester Hall (Official) [CNUTlKqSO-I].f140.m4a
[download] Destination: /youtube-dl/youtube/Above & Beyond Acoustic - Full Concert Film Live from Porchester Hall (Official) [CNUTlKqSO-I].f140.m4a
ERROR: giving up after 0 retries

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "./youtube-dl-server.py", line 70, in dl_worker
download(url, options)
File "./youtube-dl-server.py", line 116, in download
ydl.download([url])
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2017, in download
res = self.extract_info(
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
return self.process_video_result(ie_result, download=download)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1643, in process_video_result
self.process_info(new_info)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1919, in process_info
partial_success = dl(fname, new_info)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1864, in dl
return fd.download(name, info)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download
return self.real_download(filename, info_dict)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 353, in real_download
self.report_error('giving up after %s retries' % retries)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
self.ydl.report_error(*args, **kargs)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
self.trouble(error_message, tb)
File "/usr/local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries`

**Comment by aspiziri** [comment]
Just to extend on this - I also seem to sometimes get the same error/exit from other sites when downloading lengthy content so not just YouTube as I originally reported.

**Comment by aspiziri** [comment]
Confirmed to be working fine when directly running youtube-dl installed on the server FYI

**Comment by Stefan99353** [comment]
I had the same error when running on my Unraid server. Just tried to switch to host network and it is working now.

**Comment by manbearwiz** [comment]
@aspiziri I changed the way the download worker works now. If you are still using this do you want to try again with the new version?
