### ISSUE TITLE
Start issue 

### ISSUE THREAD

**Issue by MoTheCo** [manbearwiz/youtube-dl-server#80]
Hey guys every time when I want to start YouTube-dl this error message comes

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 582, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 243, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 54, in app
    response = await func(request)
  File "/home/yt-dl-server/youtube-dl-server-master/youtube-dl-server.py", line 29, in dl_queue_list
    return templates.TemplateResponse("index.html", {"request": request})
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 80, in TemplateResponse
    template = self.get_template(name)
  File "/usr/local/lib/python3.8/dist-packages/starlette/templating.py", line 67, in get_template
    return self.env.get_template(name)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

If someone could help me I would be happy thanks

**Comment by ladudu** [comment]
hi bro,look likes templates directory not found the index.html file.
could you print or check the directory?

**Comment by manbearwiz** [comment]
How are you running it? Through docker or through python directly?

**Comment by MoTheCo** [comment]
> hi bro,look likes templates directory not found the index.html file.
> could you print or check the directory?

I already tried to hard code the path with the same result

**Comment by MoTheCo** [comment]
> How are you running it? Through docker or through python directly?

I’m running it directly on my vps
