### ISSUE TITLE
some downloads failing?

### ISSUE THREAD

**Issue by jpotrz** [manbearwiz/youtube-dl-server#9]
I tired to snag a bunch of videos today and they all failed with the same error in the log:

`ERROR: Signature extraction failed: Traceback (most recent call last):`

**Comment by manbearwiz** [comment]
youtube probably changed there site a little so youtube-dl needs updating. I kicked off new docker builds that will get the new version. You can either pull the latest images from docker or shell into the running container and use pip to upgrade youtube-dl manualy.

**Comment by manbearwiz** [comment]
Just pulled the newly built image and confirmed I was able to download a video. Let me know if it still doesn't work for you.

**Comment by jpotrz** [comment]
Some videos worked. Others didn't. I'll wait for the new docker build to hit unRaid.

**Comment by manbearwiz** [comment]
Any update on this?

**Comment by jpotrz** [comment]
Yeah, it's been working fine. Thanks for the follow up.

**Comment by manbearwiz** [comment]
Glad to hear it

**Comment by D-Dogg** [comment]
Im getting is error again.
Could you built a new image?

ERROR: Signature extraction failed

`Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalteCopyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
PS C:\repos> docker logs -f 7c98209ccb6ba10b804c6d844d7f4d8062d1ac40a40029f59dee2bc9bc9c94c6
Started download thread
Bottle v0.12.16 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

172.17.0.1 - - [02/Feb/2019 10:02:58] "GET / HTTP/1.1" 404
721
172.17.0.1 - - [02/Feb/2019 10:03:04] "GET /youtube-dll HTTP/1.1" 404 743
172.17.0.1 - - [02/Feb/2019 10:03:08] "GET /youtube-dl HTTP/1.1" 200 3593
172.17.0.1 - - [02/Feb/2019 10:03:08] "GET /youtube-dl/static/style.css HTTP/1.1" 200 134
Added url https://www.youtube.com/watch?v=6jAr4UTi8mk to the download queue
172.17.0.1 - - [02/Feb/2019 10:03:15] "POST /youtube-dl/q HTTP/1.1" 200 107
[youtube] 6jAr4UTi8mk: Downloading webpage
[youtube] 6jAr4UTi8mk: Downloading video info webpage
[youtube] 6jAr4UTi8mk: Downloading js player vflehrYuM
ERROR: Signature extraction failed: Traceback (most recent
call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1134, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1201, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' %
funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see
 https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1134, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1201, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' %
funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1847, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1236, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1134, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1201, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' %
funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see
 https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete
output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./youtube-dl-server.py", line 60, in dl_worker
    download(url, options)
  File "./youtube-dl-server.py", line 106, in download
    ydl.download([url])
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2002, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 816, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 621, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 591, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1134, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1201, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' %
funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
